#!/usr/bin/env bash
# Regenerate imm-tables.h (see the header comment there for why).
set -eu
out="$(dirname "$0")/imm-tables.h"
{
  cat <<'HDR'
/* SPDX-License-Identifier: MIT */
/* GENERATED by gen-imm-tables.sh — do not edit.
 *
 * The immediate to PCMPxSTRx must be a literal, so sweeping every
 * immediate in a differential test needs one function per value.  This
 * header defines only the LIST; the caller defines X(N) twice — once to
 * emit a function, once to fill the dispatch table — so the table index
 * and the immediate are generated from the same expansion and cannot
 * drift apart.  They did once: a hand-written macro emitted $10 as
 * decimal 10 where the caller meant 0x10, and 698,452 false failures
 * made a correct emulator look 54% wrong.  Structure, not discipline,
 * is what keeps them equal now.
 *
 * All 256 values.  imm8[7] is reserved in the SDM and IGNORED by the
 * silicon — verified 2026-09-18 on a Westmere-class core: over 384,000
 * (imm, imm|0x80) pairs PCMPISTRI, PCMPISTRM and PCMPESTRI gave identical
 * results and flags, and `pcmpistri $0x8c` raises no #UD.  The emulator
 * ignores the bit too, and the sweep is what proves it.
 */
#ifndef IMM_TABLES_H
#define IMM_TABLES_H

#define IMM_EXPAND_256 \
HDR
  for n in $(seq 0 255); do
    printf '    X(%d)' "$n"
    if [ "$n" -lt 255 ]; then printf ' \\\n'; else printf '\n'; fi
  done
  printf '\n#endif\n'
} > "$out"
