#!/usr/bin/env bash
# Emit dist/linux-6.18-opemu.patch: the ONE artefact a kernel build consumes.
#
#   kernel/hook.patch            hand-maintained hunks (Kconfig, kernel/Makefile, traps.c)
#   kernel/arch/x86/...          new kernel files, verbatim (opemu.c, the matcher
#                                opemu-match.h + its vectors, asm/opemu.h)
#   core/emu-core.{c,h}          copied in as arch/x86/kernel/opemu-core.{c,h}
#
# The core is COPIED, not referenced, so the kernel tree stays self-contained
# and the differential tests in tests/ keep exercising the very bytes the
# kernel compiles.  Regenerate after touching any input; nix-configs' sse42-emu
# build regenerates and cmp's, so a stale dist/ fails that build.
set -euo pipefail
here=$(cd "$(dirname "$0")/.." && pwd)
out="$here/dist/linux-6.18-opemu.patch"
stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT

mkdir -p "$stage/b/arch/x86/kernel" "$stage/b/arch/x86/include/asm"
cp "$here/kernel/arch/x86/kernel/opemu.c"       "$stage/b/arch/x86/kernel/opemu.c"
cp "$here/kernel/arch/x86/kernel/opemu-match.h" "$stage/b/arch/x86/kernel/opemu-match.h"
cp "$here/kernel/arch/x86/kernel/opemu-match-vectors.h" "$stage/b/arch/x86/kernel/opemu-match-vectors.h"
cp "$here/kernel/arch/x86/include/asm/opemu.h"  "$stage/b/arch/x86/include/asm/opemu.h"
# the shared core, with its include rewritten to the flat kernel layout
sed 's|#include "emu-core.h"|#include "opemu-core.h"|' "$here/core/emu-core.c" > "$stage/b/arch/x86/kernel/opemu-core.c"
cp "$here/core/emu-core.h" "$stage/b/arch/x86/kernel/opemu-core.h"

{
  echo "# Generated by tools/gen-kernel-patch.sh from gt4o4/opemu-linux — do not edit."
  echo "# Adds CONFIG_X86_UD_EMULATE: user-mode #UD emulation of SSE4.2/POPCNT/AES-NI/PCLMULQDQ."
  echo
  cat "$here/kernel/hook.patch"
  cd "$stage"
  for f in arch/x86/include/asm/opemu.h arch/x86/kernel/opemu-core.h arch/x86/kernel/opemu-core.c \
           arch/x86/kernel/opemu-match.h arch/x86/kernel/opemu-match-vectors.h arch/x86/kernel/opemu.c; do
    # --label twice: headers carry the paths only, never an mtime — the
    # output must be byte-identical wherever it is regenerated (a nix
    # sandbox unpacks this tree with epoch timestamps).
    diff -Nu --label /dev/null --label "b/$f" /dev/null "b/$f" || true   # exit 1 = files differ = the point
  done
} | sed -E 's/^(\+\+\+|---) (\S+)\t.*$/\1 \2/' > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
